version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "16:ee:2f:fd:49:ca:f3:2a:ca:d5:ce:d8:ee:da:00:89"
      - run: sudo npm install npm@latest -g && sudo npm install gulp  -g
      - run: git clone git@github.com:EverFi/Skeletor.git
      - run: cd ~/test/Skeletor
      - run: npm install
      - run: gulp
