version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "16:ee:2f:fd:49:ca:f3:2a:ca:d5:ce:d8:ee:da:00:89"
      - run: git clone git@github.com:balusio/aliadas-game.git
