version: 2
jobs:
  start:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - run: mkdir components
      - add_ssh_keys:
          fingerprints:
            - "0c:1a:10:4e:4d:e9:5b:ad:5c:4d:32:70:9a:6f:7d:13"
      - run: cd components && git clone git@github.com:EverFi/Skeletor.git
      - run: ls -a
      - persist_to_workspace:
          root: ~/
          paths:
            - ./Skeletor

  test:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - run: ls -a
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/test/Skeletor
      - run: sudo npm install npm@latest -g && sudo npm install gulp  -g
      - run: cd Skeletor && npm install
      - run: cd Skeletor && gulp
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - start
      - test:
          requires:
            - start

