version: 2
jobs:
  start:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - run: mkdir components
      - checkout
      - persist_to_workspace:
          root: ~/test
          paths: components
  test:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - run: ls -a
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/test/components
      - run: sudo npm install npm@latest -g && sudo npm install gulp  -g
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - start
      - test:
          requires:
            - start

