version: 2
jobs:
  start:
    docker:
      - image: circleci/node:8.11.2-browsers
    working_directory: ~/test
    steps:
      - run: mkdir components
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - add_ssh_keys:
          fingerprints:
            - "52:fd:e6:f2:b4:88:a6:44:2e:74:20:e8:cc:a9:51:31"
      - run: cd components && git clone git@github.com:EverFi/Skeletor.git
      - run: ls -a
      - persist_to_workspace:
          root: ~/test
          paths:
            - components/Skeletor

  test:
    working_directory: ~/test
    docker:
      - image: circleci/node:8.11.2-browsers
    steps:
      - run: ls -a
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/test/Skeletor
      - run: sudo npm install npm@latest -g && sudo npm install gulp  -g
      - run: cd Skeletor && npm install
      - run: cd Skeletor && gulp
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - start
      - test:
          requires:
            - start

